//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.01 at 12:57:22 PM MSK 
//


package xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="suc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="synonyms" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}rtf"/>
 *         &lt;element ref="{}zah"/>
 *         &lt;element ref="{}tlum" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "suc",
    "synonyms",
    "comment",
    "rtf",
    "zah",
    "tlum"
})
@XmlRootElement(name = "root")
public class Root {

    @XmlElement(required = true)
    protected String suc;
    @XmlElement(required = true)
    protected String synonyms;
    protected String comment;
    @XmlElement(required = true)
    protected String rtf;
    @XmlElement(required = true)
    protected String zah;
    protected List<Tlum> tlum;

    /**
     * Gets the value of the suc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuc() {
        return suc;
    }

    /**
     * Sets the value of the suc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuc(String value) {
        this.suc = value;
    }

    /**
     * Gets the value of the synonyms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSynonyms() {
        return synonyms;
    }

    /**
     * Sets the value of the synonyms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSynonyms(String value) {
        this.synonyms = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the rtf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtf() {
        return rtf;
    }

    /**
     * Sets the value of the rtf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtf(String value) {
        this.rtf = value;
    }

    /**
     * Gets the value of the zah property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZah() {
        return zah;
    }

    /**
     * Sets the value of the zah property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZah(String value) {
        this.zah = value;
    }

    /**
     * Gets the value of the tlum property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tlum property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTlum().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tlum }
     * 
     * 
     */
    public List<Tlum> getTlum() {
        if (tlum == null) {
            tlum = new ArrayList<Tlum>();
        }
        return this.tlum;
    }

}
